apiVersion: v1
kind: ConfigMap
metadata:
  name: tf-monitoring-config
  namespace: tf-serving
data:
  monitoring.config: |-
    prometheus_config {
      enable: true,
      path: "/monitoring/prometheus/metrics"
    }
