###
### This is an ExternalSecret that proxies a Google Secret Manager secret containing
###     GSA credentials that has read-only access to the GCS bucket contiaing the models
###
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-gsa-creds
  namespace: tf-serving
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:                          # K8s secret definition
    name: tf-gsa-creds             # K8s 'Secret' object name
    creationPolicy: Owner
  dataFrom:
  - extract:
    key: tf-lite-gcr-creds       # Name of the GCPSM secret key (this needs to exist priort to use)