apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfserving-deployment
  namespace: tf-serving
  labels:
    app: tfserving-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfserving-server
  template:
    metadata:
      labels:
        app: tfserving-server
    spec:
      containers:
      - name: tf-serving-container
        image: tensorflow/serving:2.13.0
        args:
          # https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L59 -- Threads are not setup by default
          - --model_config_file=/models/models.config             # Volume Mounted below
          - --model_config_file_poll_wait_seconds=60              # Refresh config every x-seconds
          - --monitoring_config_file=/monitor/monitoring.config   # Volume mounted below
          - --prefer_tflite_model=true                            # Allows .tflite models (experimental)
          - --file_system_poll_wait_seconds=60                    # Look for new models in GCS bucket (default 300s = 5min)
          - --allow_version_labels_for_unavailable_models=true    # Required for multiple models to load
        resources:
          requests:
            cpu: "1"
            memory: "350Mi"
          limits:
            cpu: "4"
            memory: "700Mi"
        volumeMounts:
        - name: models-config
          mountPath: "/models"
          readOnly: true
        - name: monitoring-config
          mountPath: "/monitor"
          readOnly: true
        - name: tf-gsa-creds
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/creds-gcp.json
      volumes:
      - name: models-config
        configMap:
          name: models-config
      - name: monitoring-config
        configMap:
          name: tf-monitoring-config
      - name: tf-gsa-creds                                        # derived from `model-bucket-es.yaml` ExternalSecret
        secret:
          secretName: tf-gsa-creds
