apiVersion: v1
kind: Service
metadata:
  name: tf-serving-service
spec:
  type: LoadBalancer
  selector:
    app: tfserving-deployment
  ports:
  - name: grpc
    port: 8500
    targetPort: 8500
  - name: http
    port: 8501
    targetPort: 8501
